// Generated by CoffeeScript 1.6.1
(function() {
  var balance, deposit, getBalance, total, withdraw;

  total = 100;

  deposit = function(amount) {
    if (amount == null) {
      amount = 0;
    }
    return total += amount;
  };

  withdraw = function(amount) {
    if (amount == null) {
      amount = 0;
    }
    if (total >= amount) {
      return total -= amount;
    }
  };

  getBalance = function() {
    return total;
  };

  deposit(1000);

  console.log(getBalance());

  withdraw(100);

  balance = getBalance() > 0 ? getBalance() : 0;

  console.log(balance);

  withdraw(1000);

  balance = getBalance() > 0 ? getBalance() : 0;

  console.log(balance);

}).call(this);
