// Generated by CoffeeScript 1.6.1
(function() {
  var knockOnDoor, sayHello;

  knockOnDoor = function(who) {
    var i, _i, _len, _ref, _results;
    _ref = [1, 2, 3];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      _results.push(console.log("[knock knock knock] " + who));
    }
    return _results;
  };

  knockOnDoor("Penny");

  sayHello = function(what) {
    if (what == null) {
      what = "world";
    }
    return console.log("Hello, " + what);
  };

  sayHello(null);

  sayHello("William");

}).call(this);
